/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 stylized_wood_staff.glb 
Author: Manuela Reis (https://sketchfab.com/Manuela.Reis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-wood-staff-be964c8b493041cab15b449c9f966c25
Title: Stylized Wood Staff
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stylized_wood_staff.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.staff_low_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Cylinder3D1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Cylinder3D1_1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Cylinder3D1_1_copy1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.syaff_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Sphere3D1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Sphere3D2_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.PM3D_Cylinder3D1_6_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.pCylinder1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
      <mesh geometry={nodes.pCylinder2_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
    </group>
  )
}

useGLTF.preload('/stylized_wood_staff.glb')
