/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 wizard_gnome.glb 
Author: JonathanCG (https://sketchfab.com/jonathancg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizard-gnome-581405b5a63b40aba342e1356700e464
Title: Wizard Gnome
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { Color } from 'three';

const WizardGnomeHat = React.memo(function WizardGnomeHat(props) {
    const { nodes, materials } = useGLTF("/models/wizard_gnome.glb");

    const modelRef = useRef();

    useFrame((state) => {
        modelRef.current.position.y =
          -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
      });

    return (
        <group {...props} dispose={null} ref={modelRef} position={[0, 0, 0]} scale={[0.55, 0.55, 0.55]} rotation={[0.25, 0, 0]}>
          <group position={[0, -2, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group position={[0, 3, 0]}>
                <mesh geometry={nodes.Object_4.geometry} material={materials.Mtze} />
                <mesh geometry={nodes.Object_5.geometry} material={materials.Mtze} />
                <mesh geometry={nodes.Object_6.geometry} material={materials.Mtze} />
                <mesh geometry={nodes.Object_7.geometry} material={materials.Mtze} />
                <mesh geometry={nodes.Object_8.geometry} material={materials.Mtze} />
                <mesh geometry={nodes.Object_9.geometry} material={materials.Mtze} />
              </group>
             
            </group>
          </group>
        </group>
      )

})

export default WizardGnomeHat;

useGLTF.preload('/models/wizard_gnome.glb')
