
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Staff = React.memo(function Staff(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/stylized_wood_staff.glb");
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={[0.65, 0.65, 0.65]}
      position={[0, -2, 0]}
      ref={modelRef}
    >
        <mesh castShadow receiveShadow geometry={nodes.staff_low_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Cylinder3D1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Cylinder3D1_1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Cylinder3D1_1_copy1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.syaff_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Sphere3D1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Sphere3D2_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.PM3D_Cylinder3D1_6_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.pCylinder1_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
        <mesh geometry={nodes.pCylinder2_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
    </group>
  );
});

export default Staff;
useGLTF.preload("/models/stylized_wood_staff.glb");
